### ISSUE TITLE
Support mapping of attributes in all classes of the inheritance hierarchy

### ISSUE THREAD

**Issue by nfantone** [xetorthio/johm#11]
save() method in redis.clients.johm.JOhm should iterate over every superclass above the root class and add all declared fields .

```
    Class<?> superClazz = model.getClass();
    while ((superClazz = superClazz.getSuperclass()) != null) {
        fields.addAll(Arrays.asList(superClazz.getDeclaredFields()));
    }
```

get() method should, consequently, recover them in a analog fashion and fill every field:

```
        Class<?> superClazz = clazz;
        while ((superClazz = superClazz.getSuperclass()) != null) {
            for (Field field : superClazz.getDeclaredFields()) {
                fillField(hashedObject, newInstance, field);
            }
        }
```

**Comment by xetorthio** [comment]
Yes. you are probably right. I will try to fix all the pending issues over this weekend.

**Comment by nfantone** [comment]
Similar changes should be done every time model fields are needed (delete() method comes to mind).

**Comment by gsharma** [comment]
Issue to be closed/marked fixed as part of the upcoming release.

**Comment by xetorthio** [comment]
fixed on master
