### ISSUE TITLE
Support non-Model values for CollectionMap

### ISSUE THREAD

**Issue by nfantone** [xetorthio/johm#12]
Currently, this line in internalPut() at redis.clients.johm.collections.RedisMap

hash.put(key.toString(), JOhmUtils.getId(value).toString());

forces to fetch the id of the current value in a Map collection, which fails after trying to check whether it's a valid Model or not, by throwing a JOhmException ("Class pretending to be a Model but is not really annotated").

This behavior prevents the insertion of non-Model values in a Map, such as any "boxed primitive" type.

**Comment by nfantone** [comment]
Ok, I've been fooling around with this issue and finally realized that JOhm support for non-Model values for ANY Collection is not yet implemented. My bad.

**Comment by nfantone** [comment]
I believe this should be considered as a mandatory improvement for the framework. Thanks.

**Comment by gsharma** [comment]
@nfantone - I have been working on adding this feature and will attempt to do a phased collection-wise rollout in the near future. Please stay tuned.

-Gaurav
