### ISSUE TITLE
JOhm to ignore all other annotations on a model's @Id designated field

### ISSUE THREAD

**Issue by gsharma** [xetorthio/johm#16]
We need to patch JOhm to ignore all annotations but @Id on the designated id field in every model. Also need to update the documentation to reflect this. I am thinking if we could create some kind of an FAQ on the wiki, that would also be helpful for users.

**Comment by gsharma** [comment]
Issue to be closed/marked fixed as part of the upcoming release.

**Comment by xetorthio** [comment]
fixed on master
