### ISSUE TITLE
Cannot add non-johm annotations to @Id field

### ISSUE THREAD

**Issue by hertzsprung** [xetorthio/johm#31]
Using JOhm 0.5.0
Test case:
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    public @interface TestAnnotation {}

```
public class MyEntity {
    @Id @TestAnnotation private Integer id;
    // etc ...
}
```

Trying to save the entity gives the exception:
    redis.clients.johm.JOhmException: Element annotated @Id cannot have any other annotations
        at redis.clients.johm.JOhmUtils$Validator.checkValidIdType(JOhmUtils.java:323)

**Comment by hertzsprung** [comment]
This seems to be related to issue #16 (0999132dfe7a503bd7197e2ad24c268c62e9c318)

**Comment by gsharma** [comment]
Yeah, let me fix this. I think we need to do a better job of the fix for Issue 16 and ignore all JOhm-specific annotations other than the Id on id field. The patch I put in blindly ignores every other annotation but @Id.

**Comment by gsharma** [comment]
Pushed a fix on my master; will wait for the prior pull-request to be merged to make another pull-request for this patch. 

In case you want to use the patched version right away, please feel free to clone my repo: https://github.com/gsharma/johm

**Comment by xetorthio** [comment]
done, pushed to master
