### ISSUE TITLE
Out of date. Abandoned?

### ISSUE THREAD

**Issue by vito-c** [xetorthio/johm#58]
Johm is no longer compatible with the latest version of Jedis. There are 6 open pull requests that are over 9 months old. If this project has been abandoned it would be better to shut it down or put in the read me the exact version of jedis it's compatible with and that it's no longer being maintained.

**Comment by cfstras** [comment]
If you look at the [network graph](https://github.com/xetorthio/johm/network), you can see that many people have decided to take matters in their own hands.

This brings us to the question: Which fork is the "best"? Why are there so many forks not pulling from each other?

Of those forking: would you want to take over maintainership of this project, and would @xetorthio be happy with that?

**Comment by vito-c** [comment]
@cfstras Current front runners for maintainer-ship are @mockobject and @agrison I am going to open issues on each of their githubs.

**Comment by agrison** [comment]
I don't know which fork is the best or which user want to be maintainer, but what I can say is that I've forked johm some time ago and still use it actively in my projects, I've merged some interesting PR from the original repository and will try to merge PR in my fork if there is any.

xetorthio must be busy on other subjects like making Jedis awesome, but still, a simple "I won't work on that stuff anymore" would be appreciated. For the time being I appreciate the work that have been done on JOhm, but I see no problem for another maintainer to work on its fork.

**Comment by tuxillator** [comment]
@agrison will you be doing releases on your fork, or do you have a maven repo?

**Comment by agrison** [comment]
Hey @tuxillator, I don't have any maven repo to give but I can release a version somewhere if you want to :smile:  It's been time since I've uploaded an artifact on maven central and I still think it's a pain in the a*\* to do so, but I've seen that I can host a maven repository directly on my Github, I will look into this solution this weekend.

As I've said previously I'm using JOhm in 3 of my project so I really need it, that's why I'll still be working on my fork for as long as needed ;-)

**Comment by agrison** [comment]
@tuxillator Since it was really easy, I've just released a version before going out to take advantage of the blue sky outside. Please see [Use this fork](https://github.com/agrison/johm/tree/master#use-this-fork) in order to include the fork in your pom.xml

**Comment by tuxillator** [comment]
@agrison works a charm, and thanks for adding documentation!

**Comment by dpoldrugo** [comment]
I have also used @agrison fork, it works good!
I suggest to open issues on his fork: https://github.com/agrison/johm/issues

The idea was born here: https://github.com/agrison/johm/pull/3#issuecomment-214289687
